# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: bundler
    directory: '/builder'
    schedule:
      interval: daily
      time: '01:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    labels:
      - 'dependencies'
      - 'ruby'
    groups:
      rails:
        patterns:
          - 'actioncable'
          - 'actionmailbox'
          - 'actionmailer'
          - 'actionpack'
          - 'actiontext'
          - 'actionview'
          - 'activejob'
          - 'activemodel'
          - 'activerecord'
          - 'activestorage'
          - 'activesupport'
          - 'rails'
          - 'railties'
          - 'globalid'
          - 'i18n'
          - 'mail'
          - 'rack'
          - 'rackup'
      turbo:
        patterns:
          - 'turbo-rails'
          - 'stimulus-rails'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '01:00'
      timezone: Europe/Berlin
    labels:
      - 'dependencies'
      - 'gh-action'
